service: serverless-template
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    DEBUG: ${env:DEBUG, 'falllback value'},
    DATABASE_URL: ${env:DATABASE_URL, 'falllback value'}

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: '*'

custom:
  dotenv:
    exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
